{{- $name := include "kv-certs.fullname" . -}}

apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name:  "{{ $name }}-provider"
spec:
  parameters:
    cloudName: ""
    keyvaultName: {{ .Values.keyVault.name }}
    objects: |-
      array:
        {{- range $v := .Values.keyVault.certificateObjects }}
        - |
          objectName: {{ $v.objectName }}
          objectType: secret 
        {{- end }}     
        {{- range $v := .Values.keyVault.secretObjects }}
        - |
          objectName: {{ $v.objectName }}
          objectType: secret 
        {{- end }}        
    tenantId: {{ .Values.keyVault.tenantId }}
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: {{ .Values.keyVault.kubernetesUserAssignedIdentityID }}
  provider: azure
  secretObjects:
    {{- range $v := .Values.keyVault.certificateObjects }}
    - data:
      - key: tls.key
        objectName: {{ $v.objectName }}
      - key: tls.crt
        objectName: {{ $v.objectName }}
      secretName: {{ $v.secretName }}
      type: kubernetes.io/tls
    {{- end }}
    {{- range $v := .Values.keyVault.secretObjects }}
    - data:
      - key: {{ $v.secretName }}
        objectName: {{ $v.objectName }}
      secretName: {{ $v.secretName }}
      type: Opaque
    {{- end }}