{{- $name := include "kv-certs.fullname" . -}}
{{- range $k := .Values.keyVaults }}

apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name:  "{{ $name }}-provider-{{ $k.name }}"
spec:
  parameters:
    cloudName: ""
    keyvaultName: {{ $k.name }}
    objects: |-
      array:
        {{- range $v := $k.certificateObjects }}
        - |
          objectName: {{ $v.objectName }}
          objectType: secret 
        {{- end }}     
        {{- range $v := $k.secretObjects }}
        - |
          objectName: {{ $v.objectName }}
          objectType: secret 
        {{- end }}        
    tenantId: {{ $k.tenantId }}
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: {{ $k.kubernetesUserAssignedIdentityID }}
  provider: azure
  secretObjects:
    {{- range $v := $k.certificateObjects }}
    - data:
      - key: tls.key
        objectName: {{ $v.objectName }}
      - key: tls.crt
        objectName: {{ $v.objectName }}
      secretName: {{ $v.secretName }}
      type: kubernetes.io/tls
    {{- end }}
    {{- range $v := $k.secretObjects }}
    - data:
      - key: {{ $v.secretName }}
        objectName: {{ $v.objectName }}
      secretName: {{ $v.secretName }}
      type: Opaque
    {{- end }}
---
{{- end }}