{{- $name := include "kv-certs.fullname" . -}}
<<<<<<< HEAD
=======
{{- range .Values.keyVaults }}
>>>>>>> bf79371e1c250211274e6eea80b6f1332f5305cc

apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name:  "{{ $name }}-provider-{{ .name }}"
spec:
  parameters:
    cloudName: ""
    keyvaultName: {{ .name }}
    objects: |-
      array:
        {{- range .certificateObjects }}
        - |
          objectName: {{ .objectName }}
          objectType: secret 
        {{- end }}     
        {{- range .secretObjects }}
        - |
          objectName: {{ .objectName }}
          objectType: secret 
        {{- end }}        
    tenantId: {{ .tenantId }}
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: {{ .kubernetesUserAssignedIdentityID }}
  provider: azure
  secretObjects:
    {{- range .certificateObjects }}
    - data:
      - key: tls.key
        objectName: {{ .objectName }}
      - key: tls.crt
        objectName: {{ .objectName }}
      secretName: {{ .secretName }}
      type: kubernetes.io/tls
    {{- end }}
    {{- range .secretObjects }}
    - data:
      - key: {{ .secretName }}
        objectName: {{ .objectName }}
      secretName: {{ .secretName }}
      type: Opaque
    {{- end }}
---
{{- end }}
