{{- $name := include "kv-certs.fullname" . -}}

apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name:  "{{ $name }}-provider"
spec:
  parameters:
    cloudName: ""
    keyvaultName: {{ .Values.inf.kvcerts.keyVaultName }}
    objects: |-
      array:
        - |
          objectName: eshop-dev-mfgakspg-com
          objectType: secret            
    tenantId: {{ .Values.inf.kvcerts.tenantId }}
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: {{ .Values.inf.kvcerts.userAssignedIdentityID }}
  provider: azure
  secretObjects:
  - data:
    - key: tls.key
      objectName: eshop-dev-mfgakspg-com
    - key: tls.crt
      objectName: eshop-dev-mfgakspg-com
    labels:
      environment: dev
      ingress: webspa
    secretName: eshop-dev-mfgakspgcom-cert
    type: kubernetes.io/tls