apiVersion: v1
kind: ConfigMap
metadata:
  name: apim-shg-env
  namespace: {{ .Values.namespace }}
  labels:
    app: eshopondapr
data:
  config.service.endpoint: {{ .Values.gateway.apimShg.endpoint }}
  neighborhood.host: "apim-shg-instance-discovery"
  runtime.deployment.artifact.source: "Azure Portal"
  runtime.deployment.mechanism: "YAML"
  runtime.deployment.orchestrator.type: "Kubernetes"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apim-shg
  namespace: {{ .Values.namespace }}
  labels:
    app: eshopondapr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eshopondapr
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 25%
  template:
    metadata:
      labels:
        app: eshopondapr
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: apim-shg
        image: {{ .Values.gateway.apimShg.image.repository }}:{{ .Values.gateway.apimShg.image.tag }}
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8081
          # Container port used for rate limiting to discover instances
        - name: rate-limit-dc
          protocol: UDP
          containerPort: 4290
          # Container port used for instances to send heartbeats to each other
        - name: dc-heartbeat
          protocol: UDP
          containerPort: 4291
        readinessProbe:
          httpGet:
            path: /status-0123456789abcdef
            port: http
            scheme: HTTP
          initialDelaySeconds: 0
          periodSeconds: 5
          failureThreshold: 3
          successThreshold: 1
        env:
        - name: config.service.auth
          valueFrom:
            secretKeyRef:
              name: {{ .Values.gateway.apimShg.shgTokenSecret }}
              key: value
        envFrom:
        - configMapRef:
            name: apim-shg-env
---
apiVersion: v1
kind: Service
metadata:
  name: apim-shg-live-traffic
  namespace: eshoponcontainers
  labels:
    app: eshopondapr
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
  - name: http
    port: 80
    targetPort: 8080
  - name: https
    port: 443
    targetPort: 8081
  selector:
    app: eshopondapr
---
apiVersion: v1
kind: Service
metadata:
  name: apim-shg-instance-discovery
  namespace: eshoponcontainers
  labels:
    app: eshopondapr
  annotations:
    azure.apim.kubernetes.io/notes: "Headless service being used for instance discovery of self-hosted gateway"
spec:
  clusterIP: None
  type: ClusterIP
  ports:
  - name: rate-limit-discovery
    port: 4290
    targetPort: rate-limit-dc
    protocol: UDP
  - name: discovery-heartbeat
    port: 4291
    targetPort: dc-heartbeat
    protocol: UDP
  selector:
    app: eshopondapr
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: apim-shg-ingress
  namespace: eshoponcontainers
  labels:
    app: eshop
    service: apim-shg-live-traffic
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: "/$1"
spec:
  ingressClassName: nginx
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  - host: {{ .Values.hostName }}
    http:
      paths: 
      - path: /apim-shg/(.*)
        pathType: Prefix
        backend:
          service:
            name: apim-shg-live-traffic
            port: 
              number: 80