kind: ConfigMap
apiVersion: v1
metadata:
  name: catalog-cm
  namespace: {{ .Values.namespace }}
  labels:
    app: eshop
    service: catalog
data:
  ASPNETCORE_ENVIRONMENT: Development
  ASPNETCORE_URLS: http://0.0.0.0:80
  SeqServerUrl: http://seq
  APPLICATIONINSIGHTS_CONNECTION_STRING: {{ .Values.aiConnectionString }}
  PICS_FOLDER: StoreData
  DATA_FOLDER: StoreData
  LocalImageFolder: StoreData
  AzureOpenAiServiceEndpoint: {{ .Values.azureOpenAiServiceEndpoint }}
  AIProducctGeneratorPrompt: Suggest 5 Azure cloud native services. 
                             For each, create two merchandise items that could be sold on an ecommerce website store. 
                             Each merchandise should have a short cool name, description and type like mug, shirt or hoodie. Use the description and create a prompt for each merchandise item that can be used to generate an image. The prompt should be a short sentence that describes the merchandise item. 
                             All the background for the image should be transparent. Return a valid json object called suggestions containing each suggestion with a random integer id [id], a name [name], and a list of uniquely identifiable merchandise items [merchandises] for that suggestion. 
                             Each merchandize has the service name [brand], name [name], description [description], a prompt [prompt], a type [type], a global random unique integer id [id], a decimal price [price] and an integer stock [availableStock] to each merchandise item.

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: catalog
  namespace: {{ .Values.namespace }}
  labels:
    app: eshop
    service: catalog
    azure.workload.identity/use: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      service: catalog
  template:
    metadata:
      labels:
        app: eshop
        service: catalog
        azure.workload.identity/use: "true"
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "catalog-api"
        dapr.io/app-port: "80"
        dapr.io/config: "dapr-config"
        dapr.io/log-as-json: "true"
    spec:
      serviceAccountName: eshop-sa
      initContainers:
        - name: catalog-product-gen
          image: jmaksdemoacr01.azurecr.io/catalog.aigen:1.0.8
          imagePullPolicy: IfNotPresent
          #add env from a secret called azureopenai-secret
          envFrom:
            # - secretRef:
            #     name: azureopenai-credentials       
            - configMapRef:
                name: catalog-cm
          volumeMounts:
            - name: storedata
              mountPath: /app/StoreData
      containers:
        - name: catalog-api
          # image: {{ .Values.catalog.image.repository }}:{{ .Values.catalog.image.tag }}
          image: jmaksdemoacr01.azurecr.io/catalog.api:1.0.6.ai
          imagePullPolicy: {{ .Values.catalog.image.pullPolicy }}
          ports:
            - containerPort: 80
              protocol: TCP
            - containerPort: 81
              protocol: TCP
          envFrom:
            - configMapRef:
                name: catalog-cm
          resources:
            {{- toYaml .Values.catalog.resources | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /hc
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
          volumeMounts:
            - name: storedata
              mountPath: /app/StoreData
      volumes:
        # - name: storedata
        #   persistentVolumeClaim:
        #     claimName: {{ .Values.catalog.catalogDataPVC }}
        - name: storedata
          emptyDir:
            sizeLimit: 1Gi
---

kind: Service
apiVersion: v1
metadata:
  name: catalog-api
  namespace: {{ .Values.namespace }}
  labels:
    app: eshop
    service: catalog
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    - port: 3500
      targetPort: 3500
      protocol: TCP
      name: dapr-http
    - port: 50001
      targetPort: 50001
      protocol: TCP
      name: dapr-grpc
  selector:
    service: catalog
---
{{- if eq .Values.catalog.ingress.enabled true }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: catalog-ingress
  namespace: eshoponcontainers
  labels:
    app: eshop
    service: catalog-api
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: {{ .Values.ingress.className }}
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  - host: {{ .Values.hostName }}
    http:
      paths: 
      - path: /catalog(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: catalog-api
            port: 
              number: 80
{{ end }}