# K8s namespace to deploy eShopOnDapr in.
namespace: eshopondapr

# Name of host where eShopOnDapr can be accessed.
hostName: localhost


#application insights
aiConnectionString: ""
aiInstrumentationKey: ""

#blazorclient
blazorclient:
  image:
    repository: eshopdapr/blazor.client
    tag: latest
    pullPolicy: IfNotPresent
  resources: {}

#catalog API
catalog:
  image:
    repository: eshopdapr/catalog.api
    tag: latest
    pullPolicy: IfNotPresent
  ingress:
    enabled: false
  resources: {}

#Identity API
identity:
  image:
    repository: eshopdapr/identity.api
    tag: latest
    pullPolicy: IfNotPresent
  externalUrl: https://eshop.client.mfgakspg.com
  resources: {}

#Basket API
basket:
  image:
    repository: eshopdapr/basket.api
    tag: latest
    pullPolicy: IfNotPresent
  ingress:
    enabled: false
  resources: {}

#Payment API
payment:
  image:
    repository: eshopdapr/payment.api
    tag: latest
    pullPolicy: IfNotPresent
  resources: {}

#Ordering API
ordering:
  image:
    repository: eshopdapr/ordering.api
    tag: latest
    pullPolicy: IfNotPresent
  ingress:
    enabled: false
  resources: {}

#webshoppingagg
webshoppingagg:
  image:
    repository: eshopdapr/webshoppingagg
    tag: latest
    pullPolicy: IfNotPresent
  resources: {}

#gateway
gateway:
  type: Envoy
  serviceName: gateway
  envoy:
    enabled: true
    image:
      repository: eshopdapr/webshoppingapigw
      tag: latest
      pullPolicy: IfNotPresent
  apimShg:
    enabled: false
    endpoint: ""
    shgTokenSecret: ""
    image:
      repository: mcr.microsoft.com/azure-api-management/gateway
      tag: v2
  remoteGW: 
    enabled: false
    endpoint: ""


#ingress for blazor app, identity, and gateway
ingress:
  className: nginx
  tls: []
#   - hosts:
#       - localhost
#     secretName: secret
