# K8s namespace to deploy eShopOnDapr in.
namespace: eshopondapr

# Name of host where eShopOnDapr can be accessed.
hostName: localhost


#application insights
aiConnectionString: ""
aiInstrumentationKey: ""

#blazorclient
blazorclient:
  image:
    repository: eshopdapr/blazor.client
    tag: latest
    pullPolicy: IfNotPresent

#catalog API
catalog:
  image:
    repository: eshopdapr/catalog.api
    tag: latest
    pullPolicy: IfNotPresent

#Identity API
identity:
  image:
    repository: eshopdapr/identity.api
    tag: latest
    pullPolicy: IfNotPresent

#Basket API
basket:
  image:
    repository: eshopdapr/basket.api
    tag: latest
    pullPolicy: IfNotPresent

#Payment API
payment:
  image:
    repository: eshopdapr/payment.api
    tag: latest
    pullPolicy: IfNotPresent

#Ordering API
ordering:
  image:
    repository: eshopdapr/ordering.api
    tag: latest
    pullPolicy: IfNotPresent

#webshoppingagg
webshoppingagg:
  image:
    repository: eshopdapr/webshoppingagg
    tag: latest
    pullPolicy: IfNotPresent
    

#ingress for blazor app, identity, and gateway
ingress:
  tls: []
#   - hosts:
#       - localhost
#     secretName: secret
